RESSOURCE_TYPES = DATA, LEARNERS, ERRORS, STATS, INSTANCES, PREDICTIONS, BEST_HYPERPARAMS, PREPROCESSED, FILTERS = (
    "DATA", "LEARNERS", "ERRORS", "STATS", "INSTANCES", "PREDICTIONS", "BEST_HYPERPARAMS", "PREPROCESSED", "FILTERS")
